### ISSUE TITLE
Add description to trigger setting

### ISSUE THREAD

**Issue by kolobaev** [moira-alert/notifier#10]

**Comment by gmlexx** [comment]
Please, describe the desirable result in more details.

**Comment by AlexAkulov** [comment]
Он хочет что бы в письме было какое-то пояснение. 
Например: Высокая загрузка на фронте. Иди туда то и подними новый инстанс так то.

**Comment by kolobaev** [comment]
AlexAkulov все очень точно описал. Возможно такое сделать?

**Comment by gmlexx** [comment]
We can do this, but it is rather designer task, than programming.
@beevee can we get a designer for this task?

**Comment by beevee** [comment]
I will give you a design solution soon :)

**Comment by kolobaev** [comment]
как успехи?

**Comment by beevee** [comment]
I'll look into it this week.

**Comment by kolobaev** [comment]
жду недождусь

**Comment by kolobaev** [comment]
@beevee ничего еще не делали по данному вопросу?

**Comment by beevee** [comment]
Сорри, у нас тут факап, не спал уже три дня. Не доходят руки пока.

**Comment by kolobaev** [comment]
Разгреблись с факапом? не появилось минутки на мою задачку?

**Comment by kolobaev** [comment]
есть чем порадовать?

**Comment by titusjaka** [comment]
Hi, I will engage this issue. I'm going to finish it the next week. Stay tuned.

**Comment by kolobaev** [comment]
For this task all bad?

**Comment by beevee** [comment]
We are having issues with resources allocated to Moira. In fact, these issues are so bad that we decided to hire a new fulltime employee to handle them.

@titusjaka will probably have time for this task in the near future, but no promises.

Maybe you can provide a pull request yourself? It's not that hard, for this specific issue.

**Comment by beevee** [comment]
https://github.com/moira-alert/notifier/pull/19
https://github.com/moira-alert/web/pull/50
