### ISSUE TITLE
Notify Moira admins when cache is not working

### ISSUE THREAD

**Issue by beevee** [moira-alert/notifier#11]
1. Add configuration option: emergency contacts.
2. If cache stops saveing data points, send notifications to emergency contacts.

**Comment by gmlexx** [comment]
@AlexAkulov is there any progress?

**Comment by AlexAkulov** [comment]
Думаю в кэше тоже сделать счётчик вместо таймстэмпов, так же как ты сделал в чекерах.
Во-первых хочется одинаковой логики. 
Во-вторых при конфигурации с несколькими кэшами счётчик будет работать, а таймстэмпы нет. 
(Почему у нас только один кэш? в carbon-c-relay есть режим any_of который будет направлять метрики второму кэшу если первый недоступен)

**Comment by gmlexx** [comment]
Разумно

**Comment by gmlexx** [comment]
Merged heartbeat branch
