### ISSUE TITLE
Subscribe for alerts

### ISSUE THREAD

**Issue by ingtarius** [moira-alert/notifier#22]
Hello!
We are using your great software for alerting. At my point of view, it will be nice to add feature like tags subscribe for alerts.
For example, you can specify notifier destinations (mail, telegram etc) in personal settings and choose tags for monitoring (database and frontend or any others).
What do you think?

**Comment by gmlexx** [comment]
Hello, honestly I don't see the difference with how it works now :-)

**Comment by ingtarius** [comment]
Shame on me, i does not seen this button. Sorry :)
