### ISSUE TITLE
Moira & HipChat

### ISSUE THREAD

**Issue by avinchakov** [moira-alert/notifier#30]
Do you have any examples of integration with HipChat?
Module or script base?

**Comment by beevee** [comment]
Unfortunately, no. We don't have any experience with HipChat.

Good news is that writing custom plugin for HipChat requires <100 lines of fairly simple Go code. See Slack plugin, for example: https://github.com/moira-alert/notifier/blob/master/slack/slack.go

We'll be glad to see your contribution, if you'd like to make this effort. I'm ready to answer any questions and review you code.

**Comment by avinchakov** [comment]
Ok, we wil try.

**Comment by avinchakov** [comment]
Добрый день, а как добавить в GUI HipChat? Я ставил из deb пакета, править config.json не помогает.

**Comment by avinchakov** [comment]
Разобрались, все работает.
