### ISSUE TITLE
How are subscriptions defined?

### ISSUE THREAD

**Issue by warmfusion** [moira-alert/notifier#6]
I've been setting up a docker installation of Moira ( https://github.com/warmfusion/moira-docker) and while I've been able to set the cluster up and accept events (See the readme on my repo) i've yet to work out how to send notifications through Slack.

The notifier logs appear to show that its trying to do something, but is missing subscription configuration - how is this set up?

```
2016-02-14 13:16:31 DEBUG   Processing trigger id %s for metric %s == %f, %s -> %s 13ef97df-122b-4bb8-8338-1ec4b59e06de local.random.diceroll 193 WARN ERROR
2016-02-14 13:16:31 DEBUG   Getting subscriptions for tags %v [diceroll ERROR WARN]
2016-02-14 13:16:31 DEBUG   Getting tags %v subscriptions [diceroll ERROR WARN]
2016-02-14 13:16:31 DEBUG   No subscriptions found for tag set %v [diceroll ERROR WARN]
```

**Comment by gmlexx** [comment]
1. Setup possible contacts type in config.json
   https://github.com/moira-alert/web/blob/master/config.json.example
2. Open settings page
3. Fill contacts
4. +Notification. Choose tags and contact
5. Save and test

**Comment by gmlexx** [comment]
![screen shot 2016-02-14 at 19 30 05](https://cloud.githubusercontent.com/assets/1112318/13034217/767bb88a-d351-11e5-82b8-958fd8d573ee.png)

**Comment by gmlexx** [comment]
5. Save and test

**Comment by warmfusion** [comment]
Ahhhh! So THATS what the settings thing is for!

<img width="628" alt="screenshot 2016-02-14 14 34 42" src="https://cloud.githubusercontent.com/assets/2294568/13034244/32b2e020-d328-11e5-8276-67f337c0b7cd.png">

Now i'm getting somewhere!

**Comment by gmlexx** [comment]
P.S. Also i've fixed log messages.

**Comment by warmfusion** [comment]
Yup - this works like a charm!! Awesome.

<img width="474" alt="screenshot 2016-02-14 14 39 06" src="https://cloud.githubusercontent.com/assets/2294568/13034266/bb05eb2a-d328-11e5-8444-035197adb013.png">
