### ISSUE TITLE
Can't send email

### ISSUE THREAD

**Issue by m30m** [moira-alert/notifier#8]
In the notifier log this message is repeated:
`2016-03-11 13:57:24     WARNING Can't send message after X try: dial tcp :0: getsockopt: connection refused.`

**Comment by gmlexx** [comment]
It looks like smtp server reject connections. 
Notifier is trying to redeliver messages every 1 min.
This message will appear in log every 1 min for 24 hours.
After that interval message will be dropped.

**Comment by m30m** [comment]
I can telnet to the smtp server from inside the docker container. So I'm not sure what may be wrong.

**Comment by gmlexx** [comment]
Look at system log both on client and server.
